
* Introduction
  
PorGram is an open source computational grammar for Portuguese in the
HPSG formalism. It is work in progress. The long term goal is a large
coverage grammar for deep syntactic and semantic parsing of
unrestricted text.

The grammar is being developed by Leonel Figueiredo de Alencar
(@leoalenc), a computational linguist and Professor at the Federal
University of Ceará, in collaboration with Alexandre Rademaker
(@arademaker), a computer scientist with IBM Research Lab in Rio de
Janeiro and Professor at the School of Applied Mathematics of the
Getúlio Vargas Foundation (EMAp/FGV).

This effort is part of the research activities of the former as a
Visiting Professor at EMAp/FGV.  In this first stage of its
development, PorGram is being implememnted with the LinGO Grammar
Matrix (Bender, Flickinger and Oepen 2002; Bender et al. 2010):

https://matrix.ling.washington.edu/index.html

This system generates a HPSG grammar from specifications provided by
the user in a HTML questionnaire. This questionnaire covers a wide
range of grammatical phenomena in a large variety of languages. It
does not cover, however, the full range of syntactic and morphological
properties that need to be encoded in a large coverage
grammar. Therefore, additional or alternative specifications will be
manually included in the TDL source code generated by the LinGO
Grammar Matrix.  As an open source project, we invite the community to
contribute with the grammar development.

* License

  See LICENSE

* References

- Bender, Emily M., Dan Flickinger and Stephan Oepen. 2002. The
  Grammar Matrix: An Open-Source Starter-Kit for the Rapid Development
  of Cross-Linguistically Consistent Broad-Coverage Precision
  Grammars. Carroll, John, Nelleke Oostdijk, and Richard Sutcliffe,
  eds. Proceedings of the Workshop on Grammar Engineering and
  Evaluation at the 19th International Conference on Computational
  Linguistics. Taipei, Taiwan. pp. 8-14.

- Bender, Emily M., Scott Drellishak, Antske Fokkens, Laurie Poulson
  and Safiyyah Saleem. 2010. Grammar Customization. Research on
  Language and Computation 8(1):23-72.
